### ISSUE TITLE
Update Sienna-Template docs template

### ISSUE THREAD

**Issue by kennedy-mindermann** [NREL-SIIP/SIIP-Template#1]
Update `Sienna-Template` repo in NREL-Sienna with the following: 

- API pages: `internal.md` and an example for `public.md`
- `docs/` environment with `Documenter` > 1.0
- Formatter script from PSY
- `make.jl` with `makedocs` based on example in PSY

**Comment by jd-lara** [comment]
@kennedy-mindermann I think we can close this one

**Comment by kennedy-mindermann** [comment]
Closed by: https://github.com/NREL-Sienna/SiennaTemplate.jl/pull/2
